/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./src/**/*.{js,jsx,ts,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "tertiary": "#4d556b",
                "on-surface": "#0b1c30",
                "primary": "#004ac6",
                "outline-variant": "#c3c6d7",
                "secondary-fixed": "#ffddb8",
                "inverse-on-surface": "#eaf1ff",
                "on-background": "#0b1c30",
                "tertiary-fixed": "#dae2fd",
                "on-surface-variant": "#434655",
                "status-error": "#EF4444",
                "on-tertiary": "#ffffff",
                "on-error-container": "#93000a",
                "status-success": "#10B981",
                "background": "#f8f9ff",
                "surface-white": "#FFFFFF",
                "surface-container-lowest": "#ffffff",
                "secondary-fixed-dim": "#ffb95f",
                "secondary-container": "#fea619",
                "primary-container": "#2563eb",
                "surface-dim": "#cbdbf5",
                "on-primary": "#ffffff",
                "inverse-surface": "#213145",
                "error-container": "#ffdad6",
                "surface-bright": "#f8f9ff",
                "on-tertiary-container": "#eef0ff",
                "on-error": "#ffffff",
                "on-tertiary-fixed": "#131b2e",
                "outline": "#737686",
                "on-primary-container": "#eeefff",
                "error": "#ba1a1a",
                "tertiary-fixed-dim": "#bec6e0",
                "surface-variant": "#d3e4fe",
                "on-secondary-fixed": "#2a1700",
                "inverse-primary": "#b4c5ff",
                "secondary": "#855300",
                "on-secondary-fixed-variant": "#653e00",
                "on-primary-fixed": "#00174b",
                "surface": "#f8f9ff",
                "surface-tint": "#0053db",
                "surface-container-low": "#eff4ff",
                "on-secondary": "#ffffff",
                "surface-alt": "#F8FAFC",
                "on-secondary-container": "#684000",
                "on-tertiary-fixed-variant": "#3f465c",
                "on-primary-fixed-variant": "#003ea8",
                "primary-fixed": "#dbe1ff"
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            spacing: {
                "margin-desktop": "40px",
                "base": "8px",
                "gutter": "24px",
                "margin-mobile": "16px",
                "container-max": "1280px"
            }
        },
    },
    plugins: [],
}