# Server block for React Frontend
server {
    listen 80;
    server_name wildancasn.id www.wildancasn.id;

    root /var/www/wildan/frontend/build;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

# Server block for Node.js Backend API
server {
    listen 80;
    server_name api.wildancasn.id;

    # Prevent "413 Request Entity Too Large" for file uploads (e.g. transfer proof)
    client_max_body_size 10M;

    location / {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
